### ISSUE TITLE
Unable to use co_getpointvalues()

### ISSUE THREAD

**Issue by themagpipers** [jjcremmers/PyFEM#10]
Hello, I am facing a problem when I call co_getpointvalues().

My full code is 

```
import numpy as np
import time
import femm
import pyvista as pv 
import vtk

femm.openfemm()
# New magnetics problem
femm.newdocument(0)
femm.mi_probdef(20e3, 'centimeters', 'planar', 1e-8, 1, 30, 0)


def add_wire(center_pos, radius) -> None:
    x1 = center_pos[0] - radius / 2
    x2 = center_pos[0] + radius / 2
    y1 = center_pos[1]
    y2 = center_pos[1]

    femm.mi_drawarc(x1,y1,x2,y2,180,1)
    femm.mi_drawarc(x2,y2,x1,y1,180,1)

    # Add block labels at the center of each cable.
    femm.mi_addblocklabel(center_pos[0], center_pos[1])

    # Add/tag the materials to the blocks.
    femm.mi_selectlabel(center_pos[0], center_pos[1])
    femm.mi_setblockprop("Copper", 1, 0, "wires", 0, 1, 1)
    femm.mi_clearselected()

    # Add/tag the materials to the blocks.
    femm.mi_selectlabel(center_pos[0], center_pos[1])
    femm.mi_setblockprop("Copper", 1, 0, "wires", 0, 1, 1)
    femm.mi_clearselected()

# Cable 1 region.
x1 = 0.0
y1 = 0.0
x2 = 0.19
y2 = 0.0015
radius = np.sqrt((y2-y1)**2+(x2-x1)**2) / 2
cable1_x_midpoint = (x2+x1)/2
cable1_y_midpoint = (y2+y1)/2
wire_1 = add_wire((cable1_x_midpoint, cable1_y_midpoint), radius)

# Cable 2 region.
x3 = x1 + 0.2
y3 = y1 + 0.03
x4 = x2 + 0.3
y4 = y2 + 0.035

radius_2 = np.sqrt((y4-y3)**2+(x4-x3)**2) / 2
cable2_x_midpoint = (x4+x3)/2
cable2_y_midpoint = (y4+y3)/2
wire_2 = add_wire(((x4+x3)/2, (y4+y3)/2 ), radius_2)

# Add materials library.
femm.mi_addmaterial('Air')
femm.mi_addmaterial("Copper", 1, 1, 0, 0, 58)

# Add block label(s) in the surrounding air.
air_x_point = 2 * (x1 + x2 + x3 + x4)
air_y_point = 2 * (y1 + y2 + y3 + y4)
femm.mi_addblocklabel(air_x_point, air_y_point)

# Add the circuit, specifying the current in A and whether it is in parallel or series.
femm.mi_addcircprop("wires", 10, 1)

# Add/tag the materials to the blocks.
femm.mi_selectlabel(air_x_point, air_y_point)
femm.mi_setblockprop("Air", 1, 0, "<None>", 0, 0, 0)
femm.mi_clearselected()

# Boundary conditions.
femm.mi_makeABC()

# Display the generated geometry.
femm.mi_zoomnatural()

# Save the problem before analyzing.
femm.mi_saveas('automated_cable_proximity_losses.fem')

# Now,analyze the problem and load the solution when the analysis is finished
femm.mi_analyze()

femm.mi_loadsolution()

# Postprocessing.
current_density_center_0 = femm.mo_getj(cable2_x_midpoint,cable2_y_midpoint)
print(current_density_center_0)

Jx_center_0 = femm.co_getpointvalues(cable2_x_midpoint,cable2_y_midpoint)
Jy_center_0 = femm.co_getpointvalues(cable2_x_midpoint,cable2_y_midpoint)
print(current_density_center_0)
print(Jx_center_0)
print(Jy_center_0)
femm.closefemm()
```

And I get the error/traceback message:
```
Traceback (most recent call last):
  File "C:\file.py", line 128, in <module>
    Jx_center_0 = femm.co_getpointvalues(cable2_x_midpoint,cable2_y_midpoint)
  File "C:\Python3.10\lib\site-packages\femm\__init__.py", line 542, in co_getpointvalues
    return callfemm('co_getpointvalues(' + numc(x) + num(y) + ')' );
  File "C:\Python3.10\lib\site-packages\femm\__init__.py", line 156, in callfemm
    raise Exception(ErrorMsg)
Exception: error: attempt to call global `co_getpointvalues' (a nil value)
stack traceback:
   1:  main of string "lua2matlab(co_getpointvalues(0.345 0.03325)..." at line 1
```

The physical problem is successfully solved though, because I am able to retrieve the current density: `(4.7261221179732225-3.277640943875099j)`. I don't know why I cannot access to any value returned by co_getpointvalues().  
Any idea what I do wrong?

**Comment by jjcremmers** [comment]
I believe this issue is related to a different project than PyFEM.

**Comment by themagpipers** [comment]
Indeed, I am very sorry for this. It is about pyfemm.

**Comment by Dan-Dan-Danyboy** [comment]
Hello themagpipers,

I believe `co_getpointvalues(x,y)` applies for current flow problems. When executing newdocument(doctype) you chose 0 which applies to magnetics problem. So you should try with either `mo_getpointvalues(x,y)` for magnetics problems or either creating a current flow problem instead with newdocument(3)
