### ISSUE TITLE
mo_numnodes doesn't seem to work

### ISSUE THREAD

**Issue by themagpipers** [jjcremmers/PyFEM#9]
I have a PyFEMM script that works, i.e. I can set up a whole problem and solve it, it returns numbers, etc. 
I can visually see that a mesh is generated, however I would like to save it for further inspection.
Hence, I use mo_numnodes() with the hopes to retrieve the number of nodes. But this doesn't work. 
This produces the error:

```
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    num_nodes = femm.mo_numnodes()
  File "C:\Python3.10\lib\site-packages\femm\__init__.py", line 2002, in mo_numnodes
    return callfemm('mo_numnodes()');
  File "C:\Python3.10\lib\site-packages\femm\__init__.py", line 156, in callfemm
    raise Exception(ErrorMsg)
Exception: error: attempt to call global `mo_numnodes' (a nil value)
stack traceback:
   1:  main of string "lua2matlab(mo_numnodes())" at line 1
```

Anyone else having this problem?

**Comment by themagpipers** [comment]
I solved the problem by using this command after the analyze part. I had put it after the mesh creation, but this is apparently too early, the problem needs to be analyzed for this command to work.
